name: Run Tests

defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Each major Go release is supported until there are two newer major releases. https://golang.org/doc/devel/release.html#policy
        go: [1.16, 1.17, 1.18]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        run: go install golang.org/x/lint/golint@latest
      - name: lint and run tests
        run: |
          golint -set_exit_status ./...
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...